### ISSUE TITLE
turn off force engine

### ISSUE THREAD

**Issue by sOm2y** [vasturiano/three-forcegraph#10]
Hi vasturiano, great lib!!! I must say it. 
I am just wondering how do you turn off force engine since my project already have it in the serverside.
My goal is basically render nodes and links that already have coordinates.
Can you tell me specifically which function is about switching force engine on and off?
Cheers. 

Figured out by myself.

` d3ForceLayout: d3ForceSimulation()
      .force('link',null)
      .force('charge', null)
      .force('center', null)
      .stop(),`

**Comment by vasturiano** [comment]
@sOm2y great you figured out how to cancel the pre-set forces. Just wanted to add that if you're only interested in the rendering section and not the force-simulation part, you may be interested in [three-render-objects](https://github.com/vasturiano/three-render-objects) that packages up the three.js rendering scaffolding for you.

**Comment by sOm2y** [comment]
@vasturiano Found your 3d force graph and react force graph libraries, 3d force graph which includes three render objects already. You are really making my life easier. Someone please give this guys a donut ;)
