### ISSUE TITLE
Support passing request options to fetch() call in jsonUrl()

### ISSUE THREAD

**Issue by nascif** [vasturiano/three-forcegraph#14]
I found this issue while playing with 3d-force-graph. I was trying to load a JSON file with my own data, following the  async-load example, and it was failing in my environment with the following error (URL redacted). 

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://identity.XXX.com/adfs/ls/IdpInitiatedSignon.aspx?RelayState=RPID%3Dhttps%253A%252F%252FXXXX.XXX.com%252Fopensso&goto=http%3A%2F%2FYYY.ZZZcom%2...%2Fdata%2Fgraph.json with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

It looks like our intranet redirects requests through a proxy for identity checking, thus the CORS error.

The following code, an adaptation from the example in https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch, is able to retrieve the same JSON file without error.

      const getData = (url = ``, data = {}) => {
      // Default options are marked with *
        return fetch(url, {
            method: "GET", // *GET, POST, PUT, DELETE, etc.
            mode: "cors", // no-cors, cors, *same-origin
            cache: "no-cache", // *default, no-cache, reload, force-cache, only-if-cached
            credentials: "same-origin", // include, same-origin, *omit
            headers: {
                "Content-Type": "application/json; charset=utf-8",
                // "Content-Type": "application/x-www-form-urlencoded",
            },
            redirect: "follow", // manual, *follow, error
            referrer: "no-referrer", // no-referrer, *client
            //body: JSON.stringify(data), // body data type must match "Content-Type" header
        })
        .then(response => response.json()) // parses response to JSON
        .catch(error => console.error(`Fetch Error =\n`, error));
    };

    getData(`./data/graph.json`)
      .then(data => console.log(data)) // JSON from `response.json()` call
      .catch(error => console.error(error));

So exposing the second argument of the fetch() call through the jsonUrl wrapper would help in these let's-be-paranoid-and-check-our-own-files scenarios. I am afraid they might be common inside enterprise intranets.

**Comment by vasturiano** [comment]
@nascif thanks for your report! An alternative way to go about this if you need a custom fetch is to load the data yourself and then pass it to the graph via:
```
myGraph.graphData(myData)
```

`jsonUrl` is a mere convenience wrapper around the above for really simple cases. You may be better off handling the fetch config by yourself for this case.
