### ISSUE TITLE
addAttribute change to setAttribute in latest release (@1.29.2) throws error 

### ISSUE THREAD

**Issue by rodriguez-facundo** [vasturiano/three-forcegraph#22]
<img width="956" alt="Screenshot 2019-11-07 at 9 23 10 PM" src="https://user-images.githubusercontent.com/32278395/68439069-026ab280-01a5-11ea-9fa1-4ea8b4ac8b83.png">

Feel free to close it. I did not complete the issue template

**Comment by vasturiano** [comment]
@rodriguez-facundo make sure you're using a recent version of `threejs`, that supports the `setAttribute` method.
Afaict, the rename from `addAttribute` was introduced in the `0.109.0` release: https://github.com/mrdoob/three.js/releases/tag/r109

**Comment by rodriguez-facundo** [comment]
Thanks @vasturiano, that solves it. 

In my situation, I would like to keep the three version I am currently using so I  just went with @1.29.1. What I did was to run `yarn install` then modified lock to look like this:

```yarn
three-forcegraph@^1.29.0, three-forcegraph@^1.29.1:
  version "1.29.1"
  resolved "https://registry.yarnpkg.com/three-forcegraph/-/three-forcegraph-1.29.1.tgz#e914ed731324380313957dfd1207e289f3e0055f"
  integrity sha512-APKS3z0eH31nFi6s6pbm02/onUPUBmMzfJpBxHO0UZN1noRe1Sx6Eii+gdouDNQtLGYWA7//15CoY68iQt+9Vg==
  dependencies:
    accessor-fn "^1.2.2"
    d3-force-3d "^2.0.3"
    d3-scale "^3.1.0"
    d3-scale-chromatic "^1.5.0"
    data-joint "^1.2.1"
    kapsule "^1.12.1"
    ngraph.forcelayout "^1.0.0"
    ngraph.forcelayout3d "^0.0.16"
    ngraph.graph "^18.0.0"
    tinycolor2 "^1.4.1"
```

```bash
rm -rf node_modules && yarn install
```

Thanks again
