### ISSUE TITLE
Setting link width greatly slows model - possible fix?

### ISSUE THREAD

**Issue by tallhobbes** [vasturiano/three-forcegraph#28]
First off, huge thanks for sharing your amazing work!

**Issue**
I found that setting a link width to any number caused the animation loop to slow down 10x. I was using this through react-force-graph, but found a fix/workaround in three-forcegraph.module.js

The slowdown happened whenever I set ForceGraph3D's linkWidth prop to a number, even a constant. Model would slow from a locked 30fps to ~3.

**Fix?**
The fix/workaround I found is at line 308 of https://github.com/vasturiano/three-forcegraph/blob/d02d90c5b489497a08b9f91cc33a96325a35cf46/src/forcegraph-kapsule.js That's where the link's object check/assign logic is
` if (line.geometry.type !== 'CylinderBufferGeometry') {
                [removed]
                const geometry = new three.CylinderBufferGeometry(r, r, 1, state.linkResolution, 1, false);
                [removed]
                line.geometry = geometry;
              }`

I looked at the type actually being returned at time-of-check and it was just CylinderGeometry. 

Changing the check string to 'CylinderGeometry' fixed the slowdown and allowed the widths to be varied.

I tried to see if there was a difference/downside to this type, but it appears CylinderBufferGeometry is just an alias of CylinderGeometry, which itself inherits from BufferGeometry.
https://github.com/mrdoob/three.js/blob/20a41d2a4ff9ca170154a900dc2fe5eb983c1a6a/src/geometries/CylinderGeometry.js

Looks like a change may have come in [this commit](https://github.com/mrdoob/three.js/commit/7232aa40266d43e0caa128b52793574bf2c89cff)?

I hope this is helpful! Again, many thanks!!

**Comment by vasturiano** [comment]
@tallhobbes that's a great catch, thanks for surfacing this issue!

I've just published a patch for this problem. Basically I assumed the type of `CylinderBufferGeometry` objects would be `CylinderBufferGeometry`, but it's actually `CylinderGeometry`. I've added a regex match to make it future proof, in case this changes.

And yes, the fact it couldn't correctly detect the geometry type meant that it was unnecessarily re-generating the geometries, leading into a big performance penalty.

Should be much better with the latest version (`1.37.3`), could you confirm?

**Comment by tallhobbes** [comment]
@vasturiano you're a legend! Did a simple npm update with react-force-graph as the top level dependency and it all flowed through perfectly. Also quite impressed with the very readable regex.

Wonderful stuff all around, thanks again!!
