### ISSUE TITLE
Example with drei (React-Three-Drei)?

### ISSUE THREAD

**Issue by danielbakas** [vasturiano/three-forcegraph#33]
**Is your feature request related to a problem? Please describe.**
Hi!! We were wondering, what the easiest way to add a 3d-force-graph inside a R3F Canvas to use it alongside `react-three-drei` and `R3F`components 🤩

**Describe the solution you'd like**
Something similar to this:
```js
<Canvas style={{ position: "fixed" }}>
    <Suspense fallback={null}>
      {/* Camera */}
      <PerspectiveCamera makeDefault position={[0, 0.5, 10]}/>
      {/* Lighting */}
      <ambientLight args={[ambientLight.color, ambientLight.opacity]}/>
      {/* Objects */}
      <ForceGraph3D graphData={data}/>
      {/* Orbit Controls */}
      <OrbitControls ref={orbitControlsRef}/>
    </Suspense>
</Canvas>
```

**Describe alternatives you've considered**
* We tried passing something like `{new ThreeForceGraph().graphData(myData)}` as a component, as well as the `ForceGraph3D` component itself, but none worked.

**Additional context**
We are looking to work with more models than just the 3d-graph inside the canvas, and for this we would need to treat it as one more component of our Canvas, but as far as we understand the `ForceGraph3D` component is a Canvas itself.

How would you tackle this challenge? Thank you so very much! 🤩

**Comment by vasturiano** [comment]
@danielbakas you can look into the lower level component [three-forcegraph](https://github.com/vasturiano/three-forcegraph), and bring in your own ThreeJS scene scaffolding yourself. That way the 3D force graph will be just an element within your own scene / canvas.

**Comment by danielbakas** [comment]
Thank you so much for your timely response! I was checking out `theee-forcegraph` for this, precisely.

Would adding the method between curly brackets as a React child be enough?

**Comment by vasturiano** [comment]
@danielbakas I suppose that's a question for the `React-Three-Drei` framework. I'm not directly familiar with it.

**Comment by danielbakas** [comment]
Ok @vasturiano I'll ask over there. Thanks! 🤗
