### ISSUE TITLE
Reposition nodes in the graph

### ISSUE THREAD

**Issue by jesus4497** [vasturiano/three-forcegraph#36]
**Is your feature request related to a problem? Please describe.**

Hey! We would like to implement the feature of repositioning the nodes by dragging them, just as in this example: https://vasturiano.github.io/3d-force-graph/example/fix-dragged-nodes/

We are using the library with `R3F` so it is not possible for us to use [3d-force-graph](https://github.com/vasturiano/3d-force-graph) as they use their own renderer and scene.

How hard would be to implement this feature? Is there an easy way on doing so or any guidance you could provide 🙏 ?

Really appreciate the work you have done with this library, is very valuable.

Thank you in advance 🚀

**Comment by vasturiano** [comment]
Hi @jesus4497, you should look into Three's [DragControls](https://threejs.org/docs/#examples/en/controls/DragControls) object.

This is how the feature is implemented in the `3d-force-graph` package. You can look at the implementation code for reference:
https://github.com/vasturiano/3d-force-graph/blob/284e837d4e61095b01a12f93d1508d971263e6c4/src/3d-force-graph.js#L244-L248

**Comment by jesus4497** [comment]
Hi @vasturiano ! I'm using `resetCountdown` method in order to keep the engine running while dragging the nodes as you implemented in your example, I'm also using `nodePositionUpdate` method to update the object positions manually. The thing is, when I update the nodes coordinates manually, the `coords` param inside `nodePositionUpdate` are not quite the same as the ones I specified.

For example, in this line of code: https://github.com/rebeckerspecialties/threejs-tests/blob/11cb1f83db1146554dc581e7505bd3bf8f30c074/src/drawables/NodeGraph/useDrag.tsx#L283, 
I'm doing a foreach for every node that I want to change its position (my goal is to move multiple nodes at once) and updating its coords. 

Lets say I want to drag the node down, so I change node.y coords to `4.292676329612732`, the value that I get inside the `nodePositionUpdate` is `4.353615558547489`, and the larger the loop is (the array is) the wider the difference is. Even if it is just one element dragging, the values are not quite the same, there's always a small difference.

Here is the `nodePositionUpdate` method: https://github.com/rebeckerspecialties/threejs-tests/blob/11cb1f83db1146554dc581e7505bd3bf8f30c074/src/drawables/NodeGraph/NodeGraph.tsx#L122

Is there something that I'm missing in order to make this 1:1? Thank you for your support as always 🙏
