### ISSUE TITLE
NodePositionUpdate running multiple times

### ISSUE THREAD

**Issue by jesus4497** [vasturiano/three-forcegraph#37]
**Describe the bug**

I have noticed that the method `nodePositionUpdate` runs multiple times. In my case it runs 6000 - 6300 times as shown in the screenshot below. In this case, I'm just console logging the coords inside the method.

**To Reproduce**

1. Invoke the method `nodePositionUpdate` inside the `ThreeForceGraph` class. 
2. Write a console.log() inside of it to see how many times it is called.

**Expected behavior**

 I don't know if I'm missing something and this is the expected behavior! But I believe that after the coords have been settled it should stop calling the function.

**Screenshots**

![image](https://user-images.githubusercontent.com/39612839/218566496-cf2d9e9b-5656-4e3d-a95c-85f942434972.png)

**Desktop**
 - OS: macOS Ventura 13.1
 - Browser: Google Chrome
 - Version 110

**Comment by vasturiano** [comment]
@jesus4497 thanks for reaching out.

As long as the force engine is running, the coordinates are iteratively changing. During that time that function needs to be re-invoked to update the nodes' positions, at every tick of the force simulation.

**Comment by jesus4497** [comment]
@vasturiano Ack! I understand, makes sense, thanks for the quick response - closing the issue now
