### ISSUE TITLE
Issue with node color and opacity

### ISSUE THREAD

**Issue by dpan7** [vasturiano/three-forcegraph#6]
First of all, I want to point out how valuable is the work that you have done.

Please, allow me a question (maybe it is a dummy one). My issue is that I cannot change the '**color**' and '**opacity**' attributes for the nodes. I read the API, and especially for the color attribute I have used all the possible variations.

Here is a snippet of my data.json.

```
 "nodes": [
                {
                    "id": "id1",
                    "name": "name1",
                    "node-color": '0xff0000',
                    "color": 'red', // another approach 0xff0000 // another ff0000 // I tried RGB as well
                    "opacity": 1, // same thing for opacity when I change the values between [0,1]
                    "val": 1
                }
],
"links": [
                {
                    "source": "id1",
                    "target": "id2",
                    "opacity": 1,
                    "color": "#ff0000"
                }
            ]
```

Same thing applies for links. All of them present with a 'default ' grey color.
I do not know, if I misread something or it is a bug.

Thanks in advance for your help.
Pan

**Comment by vasturiano** [comment]
@dpan7 thanks for reaching out. These parameters depend on what is configured using the accessor methods `nodeColor`, `linkColor`, `nodeOpacity`, `linkOpacity`.
By default, the 'color' attributes are plucked from the node/link objects, so your example should show nodes and links as `red`. Do you have any modifications to the default on `nodeColor`/`linkColor`?

Opacity cannot be set per node/link but is instead a property of the whole graph. It can be set by doing f.e.:
```
Graph
  .nodeOpacity(0.4)
  .linkOpacity(0.1)
```

**Comment by dpan7** [comment]
Hi vasturiano,

Sorry for the late reply. I added the code for the opacity to the whole graph as you suggested and it worked!

Still, I cannot manage to make the '**color**' to work (all the nodes are showed as black). 
I have not made any modifications.

The value at the '**color**' attribute should be in HEX?

**Comment by vasturiano** [comment]
Good to hear the opacity works. The color field should be a string supporting either rgb, hex or color names. So your data syntax looks correct. Do you have an example online of your code where this is not working?

**Comment by dpan7** [comment]
I have put together a **codepen** (angular project). Unfortunately, I could not make it work with the imports, but I think that you get the notion of my code.

https://codepen.io/dpan7/project/editor/XWMezP

My goal, is to change the color of each node and later on to group nodes (under an attribute i.e. group or type) with the same color -- you ll see the attributes (gData), but I was not be able to do that either.

Honestly, I do not know what I am doing wrong.

Thanks again for your help. I much appreciated.

**Comment by vasturiano** [comment]
Thanks for the example. At a glance, I don't see anything lacking with your code. I would expect the three nodes to each have its own color (since they all have different "group").

Btw, about the imports, I notice you're not actually including the script tag for orbit controls, even though you're importing it. Could that be the issue?

**Comment by dpan7** [comment]
Yes, the desirable outcome will be to see 3 nodes having different color. However, I can see three nodes but in dark-grey color. Same thing applies when I declare the "color" attribute in my json. Again, no color changes detected :-(

Probably,this will be the issue in codepen, but in my local installation orbit controls works just fine.


**UPDATE:**  as stated in 
[https://stackoverflow.com/questions/20723040/three-js-lambert-material-color-not-showing](url)

If you have a **THREE.MeshLambertMaterial** obj you need some light in the scene, so I just added the following command for ambient light (in order to match with my scene color)
 **`this.scene.add(new THREE.AmbientLight(0xffffff))`**
and kaboom all colors (both for nodes and links) appeared and also worked the  **.nodeAutoColorBy('group')** 

I still cannot believe it was so simple... :-)

**Comment by dpan7** [comment]
Hi there,

Another issue that I have is that, I cannot change the link distance of a **specific** link.

Using the following code 

`this.myGraph.d3Force('link').distance(100);`

I was able to change the distance of all links. My goal is to change the distance of a specific link.
However, when I use something like this

`this.myGraph.d3Force('link').links(gData.links);`

in order to re-compute the links distance, **an error of missing node id was prompted**.
Changed it to the following the error disappeared, but no changes to link distances occurred.
`this.myGraph.d3Force('link').links(gData);`

Is it possible to change the distance of a specific link? For example the link of  as stated in my JSON file.

 ```
   {
         "source": "id1",
          "target": "id5",
          "distance": 150,
          "type": "1",
          "group": "2"
       }
```

Do you have any insights? Thanks again for your time.


My JSON file is the following

```
const gData = {

            "nodes": [
                {
                    "id": "id1",
                    "name": "name1",
                    "description": "Quadtree 1",
                    "type": "1",
                    "group": 1,
                    "val": 1
                },
                {
                    "id": "id2",
                    "name": "name2",
                    "description": "Quadtree 2",
                    "type": "2",
                    "group": 2,
                    "val": 2
                },
                {
                    "id": "id3",
                    "name": "name3",
                    "description": "Quadtree 3",
                    "type": "3",
                    "group": 3,
                    "val": 1
                },
                {
                    "id": "id4",
                    "name": "name4",
                    "description": "Quadtree 1",
                    "type": "1",
                    "group": 1,
                    "val": 1
                },
                {
                    "id": "id5",
                    "name": "name5",
                    "description": "Quadtree 2",
                    "type": "2",
                    "group": 2,
                    "val": 2
                },
                {
                    "id": "id6",
                    "name": "name6",
                    "description": "Quadtree 3",
                    "type": "3",
                    "group": 3,
                    "val": 1
                }
            ],
            "links": [
                {
                    "source": "id1",
                    "target": "id2",
                    "distance": 50,
                    "type": "1",
                    "group": "2"
                },
                {
                    "source": "id2",
                    "target": "id3",
                    "distance": 50,
                    "group": "1",
                    "type": "2"
                },
                {
                    "source": "id4",
                    "target": "id5",
                    "distance": 50,
                    "type": "1",
                    "group": "2"
                },
                {
                    "source": "id5",
                    "target": "id6",
                    "distance": 50,
                    "group": "1",
                    "type": "2"
                },
                {
                    "source": "id1",
                    "target": "id5",
                    "distance": 150,
                    "color": "red",
                    "group": "1",
                    "type": "2"
                }

            ]
        };
```

**Comment by vasturiano** [comment]
@dpan7 great you got the nodes colors working! Makes perfect sense that the `MeshLambertMaterial` requires light to reflect. I didn't even think of that. Nicely done. :)

About your distance question, that's interesting. Well, by looking at the docs: https://github.com/vasturiano/d3-force-3d#link_distance

It seems like you'd be able to set custom distances per link by passing an accessor function instead of a number constant. Something like:
```
this.myGraph.d3Force('link').distance(link => link.distance)
```

No need to call the `.links()` method as the data should already be bound.

I'm going purely on theory here, haven't empirically tested, so let me know if you get it working. :)

**Comment by dpan7** [comment]
Yes, you were right! It worked like a charm.

Thank you so much.
